#!/usr/bin/env ansible-playbook
---

# create single easy-access inventory file
- name: host ansible inventory
  gather_facts: false
  become: False
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: symlink the generated ansible inventory
      file: src=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory dest=../testinventory state=link force=true

# debugging fun - dump all vars to a single file #
#- hosts: all
#  become: True
#  tasks:
#    - name: dumpvars
#      template: src=dumpvars.txt.j2 dest=/tmp/dumpvars.txt
#    - name: install curl + dumpvars
#      apt: name=curl update_cache=yes cache_valid_time=3600


# install tomcat on back-end systems
- hosts: be
  become: True
  tasks:
    - include: roles/tomcat/tasks/install-tomcat.yml

# install nginx on front-end systems
- hosts: fe
  become: true
  tasks:
    - include: roles/nginxlb/tasks/install-nginx.yml


# debugging fun - get ip addrs for each system #
#- hosts: all
#  tasks: 
#    - shell: for x in $(grep -Ev "^(Inter-| face |\s*\t*lo:)" /proc/net/dev | cut -d':' -f1 | tr -d ' '|sort -n); do ip addr show $x; done
#      register: result
#    - debug: var=result.stdout_lines


# configure tomcat
- hosts: be
  gather_facts: true
  become: True
  roles:
    - tomcat

# configure nginx as lb      
- hosts: fe
  become: True
  roles:
    - nginxlb
