#!/usr/bin/env ansible-playbook
---

- hosts: be
  sudo: True
  roles:
    - tomcat

- hosts: fe
  sudo: True
  roles:
    - nginxlb

- hosts: all
  sudo: True
  tasks:
    - name: install curl
      apt: name=curl update_cache=yes cache_valid_time=3600
    - name: dumpvars
      template: src=dumpvars.txt.j2 dest=/tmp/dumpvars.txt

- name: host ansible inventory
  sudo: False
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: symlink the generated ansible inventory
      file: src=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory dest=testinventory state=link


