# -*- mode: ruby -*-
# vi: set ft=ruby :
globmem="768"
groups = {
  "be" => ["be1","be2"],
  "fe" => ["fe1"],
  "all_groups:children" => ["be", "fe"]
}


Vagrant.configure(2) do |config|

  # 1 sshkey for each os
  config.ssh.insert_key = false
  config.vm.box_check_update = false
#  config.vm.vrde = true
  
  config.vm.define "be1" do |be1|
    config.vm.hostname = "be1"
    be1.vm.box = "hashicorp/precise32"
    #be1.vm.network "private_network", type: "dhcp", auto_config: true
    #be1.vm.network "public_network", bridge: "eth0", auto_config: true
    be1.vm.network "public_network", bridge: "eth1", ip: "192.168.2.101", auto_config: true
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = globmem
    end
  end

  config.vm.define "be2" do |be2|
    config.vm.hostname = "be2"
    be2.vm.box = "hashicorp/precise32"
    #be2.vm.network "public_network", bridge: "eth0", auto_config: true
    be2.vm.network "public_network", bridge: "eth1", ip: "192.168.2.102", auto_config: true
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = globmem
    end
  end


  config.vm.define "fe1", primary: true do |fe1|
    config.vm.hostname = "fe1"
    fe1.vm.box = "hashicorp/precise32"
    fe1.vm.network "forwarded_port", guest: 22, host:10124, auto_correct: true
    fe1.vm.network "forwarded_port", guest:80, host: 8080
    #fe1.vm.network "forwarded_port", guest:443,host: 8443
    #fe1.vm.network "private_network", type: "dhcp", auto_config: true
    fe1.vm.network "public_network", bridge: "eth0", auto_config: true
    fe1.vm.network "public_network", bridge: "eth1", auto_config: true
    #fe1.vm.network "private_network", ip: "192.168.2.151", auto_config: false
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = globmem
    end

    #    fe1.vm.provision "ansible" do |ans|
    fe1.vm.provision :ansible do |ans|
      ans.playbook = "provisioning/playbook.yml"
      #ans.playbook = "nothing.yml"
      #ans.verbose = "vvv"
      ans.groups = {
        "be" => ["be1","be2"],
        "fe" => ["fe1"],
        "all_groups:children" => [ "be", "fe"]
      }
      ans.limit = 'all'
      #ans.inventory_path = ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
      
#      ans.groups = groups
    end
  end


  # "hashicorp/precise32"
  # "dreamscapes/archlinux"
  # "terrywang/archlinux"
  # boxes at https://atlas.hashicorp.com/search.

  
end
